Save document title after editing it
lblod/frontend-reglementaire-bijlage pull request #32
Opened 2022-10-06 11:44 UTC by elpoelma

This ensures that the title of the document is saved just after having edited it. An additional save of the document is no longer required. Solves https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-3734.

2022-10-10 09:08 UTC, abeforgit requested changes

2022-10-10 09:08 UTC, abeforgit commented on app/components/app-chrome.js
> +  async updateDocumentTitle(title) {
why did this become async?

2022-10-10 09:16 UTC, abeforgit commented
Probably a good idea to make it reset on blur, since now if you edit the title but dont click the checkmark, it still looks like the title was changed both on the edit page and in the overview list, but if you refresh it reverts to the old title
ember-data has some kind of rollback method which will work in this case because the title is a simple property and not a relation

2022-10-10 09:28 UTC, elpoelma commented on app/components/app-chrome.js
> +  async updateDocumentTitle(title) {
I modified it to not be async anymore.

2022-10-10 09:30 UTC, elpoelma commented
When we will refactor the AppChrome component, we should probably look into adding correct loading states/disabling buttons everywhere when saving/publishing a document or editing its title.

2022-10-21 12:00 UTC, abeforgit approved these changes

2022-10-21 14:44 UTC, merged