fix "Regulatory Attachments" button in the top bar
lblod/frontend-reglementaire-bijlage pull request #66
Opened 2023-02-16 10:15 UTC by usrtim

2023-02-16 10:38 UTC, elpoelma requested changes
The `AuMainContainer` component should be wrapping the content of the page (so the `{{outlet}}`) and not the header.

2023-02-16 11:04 UTC, abeforgit commented on app/templates/application.hbs
> +}}
an autoformatter most likely
We use prettier in our projects, but for .hbs files I'm not 100% sure if prettier handles those
We're not particularly strict about it as long as things are readable, but we do recommend formatting with prettier

2023-02-16 11:15 UTC, usrtim commented on app/templates/application.hbs
> +}}
@abeforgit yes, I'm also using prettier but I'm not sure what happend there

2023-02-16 14:16 UTC, elpoelma approved these changes

2023-02-16 16:33 UTC, abeforgit commented on app/templates/application.hbs
> +}}
well its just that this file is old and was never run through prettier

2023-02-17 13:37 UTC, usrtim commented on app/templates/application.hbs
> +}}
yes, might be

2023-02-21 15:25 UTC, merged