Add interface for being able to add a value to the codelist options
lblod/frontend-reglementaire-bijlage pull request #81
Opened 2023-05-23 10:16 UTC by lagartoverde

Needs https://github.com/lblod/app-reglementaire-bijlage/pull/52 to work

2023-05-24 12:32 UTC, x-m-el commented
-placeholder-

2023-06-02 10:09 UTC, x-m-el commented
second reviewer: @lagartoverde (can't add officially because github :shrug: )

2023-06-02 17:14 UTC, x-m-el commented
Todo:
Add a "are you sure you want to leave" pop-up when a user leaves the edit page with unsaved changes. 
Pop-up doesn't have to come if there are no changes to save.

2023-06-05 08:17 UTC, x-m-el commented
This PR also fixes https://binnenland.atlassian.net/browse/GN-4308 by limiting amount of paginations.
- wait for the comment in https://binnenland.atlassian.net/browse/GN-4308 to be resolved ("is this a good fix for this issue" question). Because if the answer is "no", code here should be changed.
- Note that the limit is set for *new* codelists. Old codelists still have this problem. **How do we fix old codelists that might have more than 20 options? Should we just check if these exist and handle them case by case (instead of a general migration)?**

2023-06-05 11:53 UTC, elpoelma requested changes
Seems to work well overall. Just noticed some translation issues mentioned in my comments. 
The ChangesetList seems like a good enough solution to tracking `hasMany` changes, maybe it could even be updated to support `hasMany-hasMany` relationships.

2023-06-05 11:53 UTC, elpoelma commented on app/components/codelist-form.hbs
> +          {{t (concat 'codelist.attr.types.' type.label)}}
```suggestion
          {{t (concat 'codelist.attr.types.' type.value)}}
```

2023-06-05 13:16 UTC, x-m-el commented
> Todo: Add a "are you sure you want to leave" pop-up when a user leaves the edit page with unsaved changes. Pop-up doesn't have to come if there are no changes to save.

I can't seem to do this cleanly for the general usecase. Only letting it show up when a user clicks cancel without saving is a possibility, but I fear this users will then lose unplanned progress by *thinking* it will also ask when they leave the page by other means.
So I think by default not doing anything is better then, as at least it is consistent...

2023-06-06 08:51 UTC, x-m-el commented
added some store cleanup (no "new" code) and checked the prod database: as far as I can tell no codelists exist yet :shrug: 
Merging :)

2023-06-06 08:52 UTC, merged